language: node_js
cache: npm
node_js:
  - "10"

services:
  - docker

before_script:
  - npm install -g codecov

script:
  - npm run test:coverage
  - npm run build
  - docker build -t mongoose-migrate .

after_script:
  - codecov

deploy:
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      tags: true

  - provider: script
    script: bash ci/docker_push.sh
    on:
      tags: true
