language: node_js
cache: npm
node_js:
  - "10"

services:
  - docker

script:
  - npm test
  - npm run build
  - docker build -t mongoose-migrate .

deploy:
  - provider: script
    script: bash ci/docker_push.sh
    on:
      all_branches: true
